/**
 * Domain Hue Resolver — a stable hue angle for every template.
 *
 * Resolves a template's place on the domain-hue spectrum in [0, 360), so the
 * topical landscape can order bands by hue even before the embedding projection
 * has run for every template. Three sources, in priority order:
 *
 *   1. `template.domainHue` — the real embedding projection (projectToHue over
 *      the topic embedding), when present. The continuous, semantically exact
 *      signal; honoured first.
 *   2. The 11 canonical anchor domains — a fixed hue per anchor, drawn straight
 *      from `domain-anchors.json` (the same anchors `projectToHue` interpolates
 *      against). Matched by domain wording so "Public Health" lands on the
 *      Healthcare anchor, "Affordable Housing" on Housing, and so on. This is
 *      what makes the spectrum stable WITHOUT an embedding backfill — the
 *      micro-ordering inside a band sharpens once `domainHue` is populated, but
 *      the band's place on the spine never depends on it.
 *   3. A deterministic hash of the domain string — for domains outside the 11
 *      anchors. Every template still gets a stable, unique hue.
 *
 * Pure, deterministic and SSR-safe: no wall-clock reads, no randomness, no
 * browser globals. The same domain string always resolves to the same hue.
 *
 * Emits a bare hue angle only — never an oklch string. The consuming component
 * applies the system's chroma-per-role via `--card-hue`, so this stays in step
 * with `app.css`'s tint/rule/icon levels and never drifts from them.
 */

import type { Template } from '$lib/types/template';
// Slim {label, hue} projection of domain-anchors.json — the 768-float embeddings
// only the server projection (domain-hue-projection.ts) reads are stripped so
// they never reach the landing bundle. Generated by scripts/gen-domain-anchors-slim.mjs.
import anchorsData from './domain-anchors-slim.json';
import { hashToHue } from './topic-hue';

interface Anchor {
	label: string;
	hue: number;
}

/** The 11 canonical anchor domains, in the canonical order of `domain-anchors.json`. */
const ANCHORS = anchorsData as Anchor[];

/**
 * Wording that resolves a template's free-text domain to a canonical anchor.
 *
 * Keys are the anchor labels exactly as they appear in `domain-anchors.json`;
 * the hue is read from that same file, so this table never re-asserts a hue —
 * it only says which words point at which anchor. Matching is lowercase
 * substring, so "Public Health" hits "health", "Labor Rights" hits "labor".
 * When a compound label matches several anchors, the most-specific (longest)
 * keyword wins (see `matchAnchor`), so modifier words do not hijack the band.
 */
const ANCHOR_KEYWORDS: Record<string, string[]> = {
	Healthcare: ['health', 'medical', 'telehealth', 'wellness'],
	Environment: ['environment', 'climate', 'energy', 'clean', 'park', 'conservation'],
	Housing: ['housing', 'urban', 'homelessness', 'vacancy', 'affordab', 'zoning'],
	Education: ['education', 'school', 'childcare', 'preschool', 'librar', 'tuition'],
	Labor: ['labor', 'worker', 'wage', 'employ', 'union', 'retail', 'pay dispar'],
	Immigration: ['immigra', 'refugee', 'asylum', 'green card', 'visa'],
	Justice: ['justice', 'criminal', 'police', 'incarcerat', 'sentenc', 'prison'],
	Governance: ['govern', 'legislat', 'congress', 'policy'],
	Technology: ['technolog', 'digital', 'privacy', 'artificial', 'data', 'cyber'],
	Transportation: [
		'transport',
		'transit',
		'infrastruc',
		'road',
		'rail',
		'parking',
		'bike',
		'bicycle',
		'freeway',
		'highway'
	],
	'Indigenous Rights': ['indigenous', 'reconcili', 'tribal', 'first nation', 'revenue sharing']
};

/** Anchor label → its hue, read once from `domain-anchors.json`. */
const HUE_BY_ANCHOR = new Map<string, number>(ANCHORS.map((a) => [a.label, a.hue]));

/** Anchor hue → its plain-English label, the inverse of `HUE_BY_ANCHOR`. */
const ANCHOR_BY_HUE = new Map<number, string>(ANCHORS.map((a) => [a.hue, a.label]));

/**
 * The plain-English anchor name a resolved hue belongs to, or null when the hue
 * is not one of the 11 canonical anchor positions (a backfilled per-template
 * projection, or a hashed unknown domain). Lets a surface caption a band by its
 * topic — "Housing", "Transportation" — instead of its free-text domain wording,
 * single-sourced from the same anchors that fix the hue so the two never drift.
 */
function anchorLabelForHue(hue: number): string | null {
	return ANCHOR_BY_HUE.get(hue) ?? null;
}

/**
 * Ordered match table: each anchor's keywords paired with its hue. Built once
 * from the anchors file so the hue is always the file's, never re-typed here.
 */
const ANCHOR_TABLE: Array<{ keywords: string[]; hue: number }> = ANCHORS.flatMap((anchor) => {
	const keywords = ANCHOR_KEYWORDS[anchor.label];
	return keywords ? [{ keywords, hue: anchor.hue }] : [];
});

/**
 * Match a free-text domain string against the canonical anchors.
 *
 * The most-specific (longest) matching keyword wins, so a compound label like
 * "Indigenous Energy Revenue Sharing" lands on Indigenous Rights (via the longer
 * "revenue sharing") rather than Environment (via "energy"), and "Urban Freeway
 * Removal" lands on Transportation (via "freeway") rather than Housing (via the
 * modifier "urban"). File order breaks exact length ties.
 *
 * @returns the anchor hue if any keyword matches, or null.
 */
function matchAnchor(text: string): number | null {
	const lower = text.toLowerCase();
	let bestHue: number | null = null;
	let bestLen = 0;
	for (const { keywords, hue } of ANCHOR_TABLE) {
		for (const keyword of keywords) {
			// Only a strictly longer match displaces the incumbent, so when two
			// anchors match keywords of equal length the earlier (file-order) one
			// holds — fully deterministic.
			if (lower.includes(keyword) && keyword.length > bestLen) {
				bestHue = hue;
				bestLen = keyword.length;
			}
		}
	}
	return bestHue;
}

/**
 * Resolve a template's domain hue in [0, 360).
 *
 * @param template - the template to place on the spectrum
 * @returns hue angle, always in [0, 360)
 */
export function resolveDomainHue(template: Pick<Template, 'domain' | 'domainHue'>): number {
	// 1. The real embedding projection, when present.
	const projected = template.domainHue;
	if (typeof projected === 'number' && projected >= 0 && projected <= 360) {
		// Fold 360 down to 0 so the range is a clean half-open [0, 360).
		return projected % 360;
	}

	// 2. A fixed hue from the 11 canonical anchors.
	const domain = typeof template.domain === 'string' ? template.domain.trim() : '';
	if (domain) {
		const anchorHue = matchAnchor(domain);
		if (anchorHue !== null) return anchorHue;
	}

	// 3. Deterministic hash of the domain string (or a stable seed when blank).
	return hashToHue(domain || 'uncategorized');
}

/** Exported for testing and for components that need the anchor hues directly. */
export { ANCHOR_TABLE, HUE_BY_ANCHOR, anchorLabelForHue, matchAnchor };
