import type { VerificationPacket } from '$lib/types/verification-packet';
import { escapeHtml } from './escape';

interface ReportContext {
	campaignId: string;
	campaignTitle: string;
	orgName: string;
	packet: VerificationPacket;
	verificationUrl: string;
	// Optional org branding (D-09). Presentation-only — these fields are
	// DELIBERATELY excluded from `canonicalPreimage` so applying a logo/accent
	// never shifts the attestation hash a recipient verifies. Populated only for
	// Coalition orgs that have set branding (the writer is Coalition-gated); when
	// absent, the report renders in the default Commons grays.
	branding?: {
		accent?: string | null;
		logoUrl?: string | null;
	};
	// Outbound white-label (D-10). When true, the "Generated by Commons" footer
	// is suppressed. The attestation block + independent-verify affordances stay
	// — only the platform attribution chrome is removed.
	whiteLabel?: boolean;
}

// Normalize a stored accent to a `#`-prefixed hex string, or null when unset /
// malformed. Mirrors the Convex-side hex gate so a corrupt value falls back to
// Commons styling rather than emitting an invalid CSS color into an email.
function normalizeAccent(accent: string | null | undefined): string | null {
	if (!accent) return null;
	const trimmed = accent.trim();
	if (!/^#?[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/.test(trimmed)) return null;
	return trimmed.startsWith('#') ? trimmed : `#${trimmed}`;
}

// Parse a normalized `#`-hex (3 or 6 digit) into rgb channels for the
// geography bar's translucent gradient. Returns null on malformed input so the
// caller can fall back to the Commons teal channels.
function hexToRgb(hex: string): { r: number; g: number; b: number } | null {
	const h = hex.replace(/^#/, '');
	const full = h.length === 3 ? h.split('').map((c) => c + c).join('') : h;
	if (full.length !== 6) return null;
	const n = parseInt(full, 16);
	if (Number.isNaN(n)) return null;
	return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

export interface RenderedReport {
	html: string;
	text: string;
	attestationHash: string;
	subject: string;
}

function fmtDate(iso: string): string {
	// Anchor to UTC explicitly so a worker rotating regions does not shift the
	// rendered date by ±1 day.
	const d = new Date(iso + 'T00:00:00Z');
	return d.toLocaleDateString('en-US', {
		month: 'short',
		day: 'numeric',
		year: 'numeric',
		timeZone: 'UTC'
	});
}

// Email-safe ratio bar via table cells. Outlook/Gmail/Apple Mail compatible.
function ratioBar(
	segments: Array<{ pct: number; color: string }>,
	height: number = 4
): string {
	const cells = segments
		.filter((s) => s.pct > 0)
		.map(
			(s) =>
				`<td style="width:${s.pct}%;height:${height}px;background-color:${s.color};font-size:0;line-height:0;">&nbsp;</td>`
		)
		.join('');

	return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-radius:2px;overflow:hidden;"><tr>${cells}</tr></table>`;
}

// Canonical preimage for the attestation hash. Includes the substrate fields a
// staffer reads in the email so any silent change shifts the hash. Domain-
// prefixed (`voter-protocol-report-v1`) so future preimage changes cut a clean
// version line. The verificationUrl is intentionally NOT in the preimage —
// it is environment-coupled (PUBLIC_BASE_URL differs per deployment) and
// would make staging vs prod hashes diverge for the same data; we use the
// deployment-agnostic `campaignId` instead.
export function canonicalPreimage(ctx: ReportContext): string {
	const { campaignId, campaignTitle, orgName, packet } = ctx;
	const { verified, districtCount, authorship, dateRange, identityBreakdown, geography, debate } =
		packet;
	const ib = identityBreakdown
		? `${identityBreakdown.govId}|${identityBreakdown.addressVerified}|${identityBreakdown.emailOnly}`
		: '';
	// Sort by count desc (matches the visible bar-chart ordering) with hash
	// ascending as tiebreaker (deterministic when counts tie). Without this
	// alignment a malicious input could permute the visible chart away from
	// the hashed ordering while the hash held  — see hash-ordering note.
	const geo = (geography ?? [])
		.slice()
		.sort((a, b) =>
			b.count !== a.count ? b.count - a.count : a.hash.localeCompare(b.hash),
		)
		.map((g) => `${g.hash}=${g.count}`)
		.join(',');
	// Debate field — only contributes to the preimage when present, otherwise
	// emits an empty string so pre-debate campaigns keep their existing hash
	// stable.
	const debatePreimage = debate
		? [
				debate.marketPosition,
				debate.totalStake,
				debate.topArgumentScore,
				debate.aiPanelConsensus === null ? '' : String(debate.aiPanelConsensus),
				debate.participantCount === null ? '' : String(debate.participantCount),
				debate.resolutionHash ?? ''
			].join('|')
		: '';
	return [
		'voter-protocol-report-v1',
		`campaign:${campaignId}`,
		campaignTitle,
		orgName,
		String(verified),
		String(districtCount),
		ib,
		`${authorship.individual}|${authorship.shared}|${authorship.explicit ? 1 : 0}`,
		`${dateRange.earliest}|${dateRange.latest}|${dateRange.spanDays}`,
		geo,
		debatePreimage
	].join('\n---\n');
}

async function sha256Hex(input: string): Promise<string> {
	const bytes = new TextEncoder().encode(input);
	const digest = await crypto.subtle.digest('SHA-256', bytes);
	return Array.from(new Uint8Array(digest))
		.map((b) => b.toString(16).padStart(2, '0'))
		.join('');
}

function renderHtml(ctx: ReportContext, attestationHash: string): string {
	const { campaignTitle, orgName, packet, verificationUrl } = ctx;
	const { verified, districtCount, authorship, dateRange, identityBreakdown } = packet;

	// Branding (D-09): accent overrides the default Commons teal for the eyebrow
	// header, ratio-bar primary segments, and the independent-verify link. Logo
	// renders in the header when present. Both fall back to Commons styling when
	// unset. `#3bc4b8` is the existing Commons teal default.
	const accent = normalizeAccent(ctx.branding?.accent);
	const primary = accent ?? '#3bc4b8';
	const logoUrl = ctx.branding?.logoUrl ?? null;

	let identityHtml = '';
	if (identityBreakdown) {
		const total = identityBreakdown.govId + identityBreakdown.addressVerified + identityBreakdown.emailOnly;
		if (total > 0) {
			const parts: string[] = [];
			if (identityBreakdown.govId > 0) parts.push(`${identityBreakdown.govId} government ID`);
			if (identityBreakdown.addressVerified > 0) parts.push(`${identityBreakdown.addressVerified} address verified`);
			if (identityBreakdown.emailOnly > 0) parts.push(`${identityBreakdown.emailOnly} email`);

			const bar = ratioBar([
				{ pct: Math.round((identityBreakdown.govId / total) * 100), color: '#10b981' },
				{ pct: Math.round((identityBreakdown.addressVerified / total) * 100), color: primary },
				{ pct: Math.round((identityBreakdown.emailOnly / total) * 100), color: '#d4d4d4' }
			]);

			identityHtml = `
          <tr>
            <td style="padding:12px 0 4px 0;">
              <p style="margin:0;font-size:13px;color:#525252;">${escapeHtml(parts.join(' · '))}</p>
            </td>
          </tr>
          <tr>
            <td style="padding:0 0 8px 0;">${bar}</td>
          </tr>`;
		}
	}

	let authorshipHtml = '';
	const authorTotal = authorship.individual + authorship.shared;
	if (authorTotal > 0) {
		const parts: string[] = [];
		if (authorship.individual > 0) {
			parts.push(`${authorship.individual} ${authorship.explicit ? 'individually composed' : 'distinct messages'}`);
		}
		if (authorship.shared > 0) {
			parts.push(`${authorship.shared} shared ${authorship.shared === 1 ? 'statement' : 'statements'}`);
		}

		const bar = ratioBar([
			{ pct: Math.round((authorship.individual / authorTotal) * 100), color: '#10b981' },
			{ pct: Math.round((authorship.shared / authorTotal) * 100), color: '#d4d4d4' }
		]);

		authorshipHtml = `
          <tr>
            <td style="padding:4px 0 4px 0;">
              <p style="margin:0;font-size:13px;color:#525252;">${escapeHtml(parts.join(' · '))}</p>
            </td>
          </tr>
          <tr>
            <td style="padding:0 0 8px 0;">${bar}</td>
          </tr>`;
	}

	let geographyHtml = '';
	if (packet.geography && packet.geography.length > 1) {
		const geoTotal = packet.geography.reduce((s, d) => s + d.count, 0);
		// Same sort as the canonical preimage so what the staffer sees in the
		// bar chart is the same ordering bound by the attestation hash.
		const sortedGeography = packet.geography
			.slice()
			.sort((a, b) =>
				b.count !== a.count ? b.count - a.count : a.hash.localeCompare(b.hash),
			);
		const topDistricts = sortedGeography.slice(0, 8);

		const rgb = hexToRgb(primary) ?? { r: 59, g: 196, b: 184 };
		const bar = ratioBar(
			topDistricts.map((d, i) => ({
				pct: Math.round((d.count / geoTotal) * 100),
				color:
					i === 0
						? primary
						: `rgba(${rgb.r},${rgb.g},${rgb.b},${Math.max(0.25, 0.8 - i * 0.08)})`
			}))
		);

		geographyHtml = `
          <tr>
            <td style="padding:4px 0 4px 0;">
              <p style="margin:0;font-size:13px;color:#525252;">${districtCount} ${districtCount === 1 ? 'community' : 'communities'} represented</p>
            </td>
          </tr>
          <tr>
            <td style="padding:0 0 8px 0;">${bar}</td>
          </tr>`;
	} else {
		geographyHtml = `
          <tr>
            <td style="padding:4px 0 8px 0;">
              <p style="margin:0;font-size:13px;color:#525252;">${districtCount} ${districtCount === 1 ? 'community' : 'communities'} represented</p>
            </td>
          </tr>`;
	}

	let temporalHtml = '';
	if (dateRange.spanDays > 0) {
		temporalHtml = `
          <tr>
            <td style="padding:4px 0 8px 0;">
              <p style="margin:0;font-size:13px;color:#525252;">Submissions ${escapeHtml(fmtDate(dateRange.earliest))} – ${escapeHtml(fmtDate(dateRange.latest))}</p>
            </td>
          </tr>`;
	}

	// Org logo header — rendered above the "Constituent Report" eyebrow when a
	// branding logo is set. Capped height keeps the email shell intact.
	const logoHtml = logoUrl
		? `
          <tr>
            <td style="padding:0 0 20px 0;">
              <img src="${escapeHtml(logoUrl)}" alt="${escapeHtml(orgName)}" style="max-height:40px;max-width:200px;display:block;border:0;" />
            </td>
          </tr>`
		: '';

	// Eyebrow accent — defaults to the muted Commons gray; an org accent tints
	// it. The "Constituent Report" wording is never branded away.
	const eyebrowColor = accent ?? '#a3a3a3';

	// Platform attribution footer (D-10). Suppressed under white-label; the
	// attestation block + independent-verify affordances above are untouched.
	const generatedFooter = ctx.whiteLabel
		? ''
		: `
          <tr>
            <td style="padding:32px 0 0 0;">
              <p style="margin:0;font-size:11px;color:#a3a3a3;line-height:1.6;">
                Generated by Commons. Constituent emails are encrypted under a
                per-organization key; the platform decrypts them only at send
                time and does not retain plaintext.
              </p>
            </td>
          </tr>`;

	return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Constituent Report — ${escapeHtml(campaignTitle)}</title>
</head>
<body style="margin:0;padding:0;background-color:#fafaf9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#fafaf9;">
    <tr>
      <td align="center" style="padding:40px 20px;">
        <table role="presentation" width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
          ${logoHtml}
          <tr>
            <td style="padding:0 0 32px 0;">
              <p style="margin:0;font-size:12px;font-weight:600;color:${eyebrowColor};text-transform:uppercase;letter-spacing:0.08em;">
                Constituent Report
              </p>
            </td>
          </tr>

          <tr>
            <td style="padding:0 0 8px 0;">
              <p style="margin:0;font-size:18px;font-weight:600;color:#171717;line-height:1.4;">
                ${escapeHtml(campaignTitle)}
              </p>
            </td>
          </tr>
          <tr>
            <td style="padding:0 0 28px 0;">
              <p style="margin:0;font-size:13px;color:#737373;">
                from ${escapeHtml(orgName)}
              </p>
            </td>
          </tr>

          <tr>
            <td style="padding:24px 0;border-top:1px solid #e5e5e5;border-bottom:1px solid #e5e5e5;">
              <p style="margin:0 0 4px 0;font-size:36px;font-weight:700;color:#171717;font-family:'Courier New',Courier,monospace;">
                ${verified.toLocaleString()}
              </p>
              <p style="margin:0;font-size:15px;color:#525252;">
                constituents across ${districtCount} ${districtCount === 1 ? 'community' : 'communities'}
              </p>
              ${
								authorship.individual > 0
									? `<p style="margin:8px 0 0 0;font-size:15px;font-weight:600;color:#171717;">
                ${authorship.individual.toLocaleString()} individually composed ${authorship.individual === 1 ? 'message' : 'messages'}
              </p>`
									: ''
							}
            </td>
          </tr>

          <tr>
            <td style="padding:20px 0 0 0;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                ${identityHtml}
                ${authorshipHtml}
                ${geographyHtml}
                ${temporalHtml}
                <tr>
                  <td style="padding:4px 0;">
                    <p style="margin:0;font-size:13px;color:#737373;">One submission per person. Duplicates removed.</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr>
            <td style="padding:28px 0 0 0;">
              <table role="presentation" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="background-color:#f5f5f4;border:1px solid #e5e5e5;border-radius:6px;padding:12px 20px;">
                    <a href="${escapeHtml(verificationUrl)}" style="font-size:13px;color:${accent ?? '#525252'};text-decoration:none;">
                      Verify these claims independently &rarr;
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr>
            <td style="padding:24px 0 0 0;">
              <p style="margin:0;font-size:11px;color:#a3a3a3;line-height:1.6;">
                Attestation hash · recompute the canonical preimage from the verification page to confirm this report.
              </p>
              <p style="margin:4px 0 0 0;font-size:11px;color:#525252;line-height:1.6;font-family:'Courier New',Courier,monospace;letter-spacing:0.02em;word-break:break-all;">
                sha256:${escapeHtml(attestationHash)}
              </p>
              <p style="margin:4px 0 0 0;font-size:11px;color:#a3a3a3;line-height:1.6;">
                Spec: <a href="https://github.com/communisaas/voter-protocol/blob/main/specs/REPORT-ATTESTATION-SPEC.md" style="color:#525252;text-decoration:underline;">REPORT-ATTESTATION-SPEC v1</a>
              </p>
            </td>
          </tr>

          ${generatedFooter}

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function renderText(ctx: ReportContext, attestationHash: string): string {
	const { campaignTitle, orgName, packet, verificationUrl } = ctx;
	const { verified, districtCount, authorship, dateRange, identityBreakdown, geography } = packet;
	const rule = '─'.repeat(48);
	const lines: string[] = [];

	lines.push('CONSTITUENT REPORT');
	lines.push('');
	lines.push(campaignTitle);
	lines.push(`from ${orgName}`);
	lines.push('');
	lines.push(rule);
	lines.push(
		`${verified.toLocaleString()} constituents across ${districtCount} ${districtCount === 1 ? 'community' : 'communities'}`
	);
	if (authorship.individual > 0) {
		lines.push(
			`${authorship.individual.toLocaleString()} individually composed ${authorship.individual === 1 ? 'message' : 'messages'}`
		);
	}
	lines.push(rule);

	if (identityBreakdown) {
		const total =
			identityBreakdown.govId + identityBreakdown.addressVerified + identityBreakdown.emailOnly;
		if (total > 0) {
			lines.push('');
			lines.push('Identity composition:');
			if (identityBreakdown.govId > 0) lines.push(`  - ${identityBreakdown.govId} government ID`);
			if (identityBreakdown.addressVerified > 0)
				lines.push(`  - ${identityBreakdown.addressVerified} address verified`);
			if (identityBreakdown.emailOnly > 0) lines.push(`  - ${identityBreakdown.emailOnly} email`);
		}
	}

	const authorTotal = authorship.individual + authorship.shared;
	if (authorTotal > 0) {
		lines.push('');
		lines.push('Authorship:');
		if (authorship.individual > 0) {
			lines.push(
				`  - ${authorship.individual} ${authorship.explicit ? 'individually composed' : 'distinct messages'}`
			);
		}
		if (authorship.shared > 0) {
			lines.push(
				`  - ${authorship.shared} shared ${authorship.shared === 1 ? 'statement' : 'statements'}`
			);
		}
	}

	if (geography && geography.length > 0) {
		const geoTotal = geography.reduce((s, d) => s + d.count, 0);
		const sorted = geography
			.slice()
			.sort((a, b) =>
				b.count !== a.count ? b.count - a.count : a.hash.localeCompare(b.hash),
			);
		const top = sorted.slice(0, 8);
		const topShare = geoTotal > 0
			? Math.round((top.reduce((s, d) => s + d.count, 0) / geoTotal) * 100)
			: 0;
		lines.push('');
		lines.push('Geography:');
		lines.push(
			`  ${districtCount} ${districtCount === 1 ? 'community' : 'communities'} represented; top ${top.length} carry ${topShare}% of contacts.`
		);
		lines.push(
			'  District identifiers are hashed at the platform layer; aggregate-only.'
		);
	}

	if (dateRange.spanDays > 0) {
		lines.push('');
		lines.push(`Submissions: ${fmtDate(dateRange.earliest)} – ${fmtDate(dateRange.latest)}`);
	}

	lines.push('');
	lines.push('One submission per person. Duplicates removed.');
	lines.push('');
	lines.push(rule);
	lines.push('');
	lines.push('Verify these claims independently:');
	lines.push(`  ${verificationUrl}`);
	lines.push('');
	lines.push(`Attestation: sha256:${attestationHash}`);
	lines.push(
		'  Recompute via REPORT-ATTESTATION-SPEC v1 at:'
	);
	lines.push(
		'  https://github.com/communisaas/voter-protocol/blob/main/specs/REPORT-ATTESTATION-SPEC.md'
	);
	lines.push('');
	// T8-4a — Offline verify block. If Commons.email is unreachable or the
	// org distrusts the platform's verify URL, any SHA-256 implementation can
	// reproduce this attestation from the listed fields. Order matters: must
	// match `canonicalPreimage` exactly.
	lines.push(rule);
	lines.push('');
	lines.push('Verify offline (no Commons URL required):');
	lines.push('');
	lines.push('  Compute SHA-256 of the following fields joined with the line');
	lines.push("  separator '\\n---\\n':");
	lines.push('');
	lines.push('    voter-protocol-report-v1');
	lines.push(`    campaign:${ctx.campaignId}`);
	lines.push(`    ${ctx.campaignTitle}`);
	lines.push(`    ${ctx.orgName}`);
	lines.push(`    ${verified}`);
	lines.push(`    ${districtCount}`);
	lines.push(
		`    ${identityBreakdown ? `${identityBreakdown.govId}|${identityBreakdown.addressVerified}|${identityBreakdown.emailOnly}` : '(no identity breakdown)'}`
	);
	lines.push(
		`    ${authorship.individual}|${authorship.shared}|${authorship.explicit ? 1 : 0}`
	);
	lines.push(`    ${dateRange.earliest}|${dateRange.latest}|${dateRange.spanDays}`);
	lines.push(
		`    ${(geography ?? [])
			.slice()
			.sort((a, b) =>
				b.count !== a.count ? b.count - a.count : a.hash.localeCompare(b.hash)
			)
			.map((g) => `${g.hash}=${g.count}`)
			.join(',') || '(empty)'}`
	);
	lines.push('');
	lines.push('  Result must equal the attestation hash above.');
	lines.push('  Any platform-independent SHA-256 tool reproduces it:');
	lines.push('    printf "<lines>" | shasum -a 256');
	lines.push('');
	lines.push(rule);
	// Platform attribution (D-10): suppressed under white-label. The offline-
	// verify block above stays — it is the independent-verify affordance, not
	// Commons branding chrome.
	if (!ctx.whiteLabel) {
		lines.push('');
		lines.push('Generated by Commons. Independently verifiable.');
		lines.push('Constituent emails are encrypted under a per-organization key;');
		lines.push('the platform decrypts them only at send time and does not retain');
		lines.push('plaintext.');
	}

	return lines.join('\n');
}

export function reportSubject(campaignTitle: string, verified: number): string {
	return `${campaignTitle} — ${verified.toLocaleString()} constituents reached`;
}

export async function renderReport(ctx: ReportContext): Promise<RenderedReport> {
	const attestationHash = await sha256Hex(canonicalPreimage(ctx));
	return {
		html: renderHtml(ctx, attestationHash),
		text: renderText(ctx, attestationHash),
		attestationHash,
		subject: reportSubject(ctx.campaignTitle, ctx.packet.verified)
	};
}
