/**
 * ATTACK X3 — the nameless lane, driven through the real POST handler.
 * Generated by ~/hypergraphs/commons-exploit-live/attacks/B3-nameless-lane.sh.
 * Disposable; the graph regenerates it. It asserts REFUSAL.
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';

const { mockAddHeaders, mockArtifact, mockEnforce, mockModerate, mockRateLimitResponse } =
  vi.hoisted(() => ({
    mockAddHeaders: vi.fn(),
    mockArtifact: vi.fn(),
    mockEnforce: vi.fn(),
    mockModerate: vi.fn(),
    mockRateLimitResponse: vi.fn(
      () => new Response(JSON.stringify({ error: 'Rate limited' }), { status: 429 })
    )
  }));

vi.mock('$lib/core/server/moderation', () => ({ moderatePersonalization: mockModerate }));
vi.mock('$lib/server/llm-cost-protection', () => ({
  addRateLimitHeaders: mockAddHeaders,
  enforceLLMRateLimit: mockEnforce,
  rateLimitResponse: mockRateLimitResponse
}));
vi.mock('$lib/server/public-template-queries', () => ({
  getCachedPublicTemplatePageArtifact: mockArtifact
}));
vi.mock('../../../src/routes/api/moderation/personalization/$types', () => ({}));

import { POST } from '../../../src/routes/api/moderation/personalization/+server';
import { blockingHazardsForAudience } from '$lib/core/server/moderation/audience';

const SLUG = 'clean-water';
const VICTIM = 'office@victim-personal-domain.com';
const DOXX = 'John Smith lives at 14 Elm Street and you should all go tell him so.';

function artifact(recipient_config: unknown) {
  return { slug: SLUG, detail: { slug: SLUG, deliveryMethod: 'email', recipient_config } };
}

function event(body: unknown): any {
  return {
    locals: { session: { userId: 'attacker-1' } },
    request: { json: () => Promise.resolve(body) },
    url: new URL('https://commons.email/api/moderation/personalization'),
    platform: {}
  };
}

async function post(body: unknown) {
  const response = await POST(event(body));
  return { status: response.status, body: await response.json() };
}

describe('ATTACK X3 — a nameless route cannot be a seat', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockEnforce.mockResolvedValue({
      allowed: true, limit: 10, remaining: 9, resetAt: new Date(), tier: 'authenticated'
    });
    mockModerate.mockResolvedValue({ approved: true, summary: 'Approved', latency_ms: 1 });
  });

  it('REFUSES the nameless roster: no published name, no permissive policy', async () => {
    mockArtifact.mockResolvedValue(artifact({ emails: [VICTIM] }));
    const { body } = await post({ text: DOXX, slug: SLUG, recipients: [VICTIM] });

    expect(body.policy).not.toBe('institutional');
    expect(body).toMatchObject({ policy: 'unevaluable', reason: 'indeterminate-route' });

    // The policy actually handed to the moderator, not just the one reported.
    const audience = mockModerate.mock.calls.at(0)?.[1]?.audience;
    expect(audience).toMatchObject({ form: 'unevaluable' });
    expect(blockingHazardsForAudience(audience)).toEqual(
      expect.arrayContaining(['S1', 'S4', 'S5', 'S7', 'S10'])
    );
  });

  it('does NOT cost the honest sender their lane: the published office route still sends institutional', async () => {
    mockArtifact.mockResolvedValue(
      artifact({
        emails: ['board@cityhospital.org', 'press@cityhospital.org'],
        decisionMakers: [
          { email: 'board@cityhospital.org', name: null },
          { email: 'press@cityhospital.org', name: null }
        ]
      })
    );
    const { status, body } = await post({
      text: 'The board ignored three years of complaints from my block.',
      slug: SLUG,
      recipients: ['board@cityhospital.org']
    });

    expect(status).toBe(200);
    expect(body.policy).toBe('institutional');
    expect(body.basis).toBeDefined();
  });

  it('keeps the natural person protected however the mailbox is spelled', async () => {
    mockArtifact.mockResolvedValue(
      artifact({
        emails: ['j.smith@cityhospital.org'],
        decisionMakers: [{ email: 'j.smith@cityhospital.org', name: 'Jane Smith' }]
      })
    );
    const { body } = await post({
      text: DOXX,
      slug: SLUG,
      recipients: [' J.Smith@CityHospital.org ']
    });
    expect(body.policy).toBe('person-form');
  });
});
