/**
 * ATTACK X1 — the caller selects the policy by naming someone else's slug.
 * Generated by ~/hypergraphs/commons-exploit-live/attacks/B1-cross-slug.sh.
 * Disposable; the graph regenerates it. It asserts REFUSAL.
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';

const { mockAddHeaders, mockArtifact, mockEnforce, mockModerate, mockRateLimitResponse } =
  vi.hoisted(() => ({
    mockAddHeaders: vi.fn(),
    mockArtifact: vi.fn(),
    mockEnforce: vi.fn(),
    mockModerate: vi.fn(),
    mockRateLimitResponse: vi.fn(
      () => new Response(JSON.stringify({ error: 'Rate limited' }), { status: 429 })
    )
  }));

vi.mock('$lib/core/server/moderation', () => ({ moderatePersonalization: mockModerate }));
vi.mock('$lib/server/llm-cost-protection', () => ({
  addRateLimitHeaders: mockAddHeaders,
  enforceLLMRateLimit: mockEnforce,
  rateLimitResponse: mockRateLimitResponse
}));
vi.mock('$lib/server/public-template-queries', () => ({
  getCachedPublicTemplatePageArtifact: mockArtifact
}));
vi.mock('../../../src/routes/api/moderation/personalization/$types', () => ({}));

import { POST } from '../../../src/routes/api/moderation/personalization/+server';

const VICTIM = 'john.smith@smithproperties.com';
const COVER_SLUG = 'clean-water';
const DOXX = 'John Smith lives at 14 Elm Street and you should all go tell him so.';

function institutionalArtifact(deliveryMethod = 'email') {
  return {
    slug: COVER_SLUG,
    detail: {
      slug: COVER_SLUG,
      deliveryMethod,
      recipient_config: { emails: ['board@cityhospital.org', 'press@cityhospital.org'] }
    }
  };
}

function event(body: unknown): any {
  return {
    locals: { session: { userId: 'attacker-1' } },
    request: { json: () => Promise.resolve(body) },
    url: new URL('https://commons.email/api/moderation/personalization'),
    platform: {}
  };
}

async function post(body: unknown) {
  const response = await POST(event(body));
  return { status: response.status, body: await response.json() };
}

describe('ATTACK X1 — slug is not a policy selector', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockEnforce.mockResolvedValue({
      allowed: true, limit: 10, remaining: 9, resetAt: new Date(), tier: 'authenticated'
    });
    mockModerate.mockResolvedValue({ approved: true, summary: 'Approved', latency_ms: 1 });
    mockArtifact.mockResolvedValue(institutionalArtifact());
  });

  it('REFUSES the cross-slug grant: addressing a victim under a cover slug is unevaluable', async () => {
    const { body } = await post({ text: DOXX, slug: COVER_SLUG, recipients: [VICTIM] });
    expect(body.policy).not.toBe('institutional');
    expect(body).toMatchObject({ policy: 'unevaluable', reason: 'addressee-not-published' });
    expect(mockModerate).toHaveBeenCalledWith(
      DOXX,
      expect.objectContaining({ audience: expect.objectContaining({ form: 'unevaluable' }) })
    );
  });

  it('REFUSES the bare-slug grant: no addressed recipients is strict, before any artifact read', async () => {
    const { body } = await post({ text: DOXX, slug: COVER_SLUG });
    expect(body).toMatchObject({ policy: 'unevaluable', reason: 'no-addressed-recipients' });
    expect(mockArtifact).not.toHaveBeenCalled();
  });

  it('REFUSES the same grant when the cover slug rides the certified lane', async () => {
    mockArtifact.mockResolvedValue(institutionalArtifact('cwc'));
    const { body } = await post({ text: DOXX, slug: COVER_SLUG });
    expect(body.policy).not.toBe('institutional');
  });

  it('does NOT cost the honest sender their lane: addressed within published roster stays institutional', async () => {
    const { status, body } = await post({
      text: 'The board ignored three years of complaints from my block.',
      slug: COVER_SLUG,
      recipients: ['board@cityhospital.org']
    });
    expect(status).toBe(200);
    expect(body.policy).toBe('institutional');
  });

  it('keeps the natural person protected however the mailbox is spelled', async () => {
    mockArtifact.mockResolvedValue({
      slug: COVER_SLUG,
      detail: {
        slug: COVER_SLUG,
        deliveryMethod: 'email',
        recipient_config: {
          emails: ['board@cityhospital.org'],
          decisionMakers: [{ name: 'John Smith', email: VICTIM }]
        }
      }
    });
    const { body } = await post({
      text: DOXX,
      slug: COVER_SLUG,
      recipients: [' John.Smith@SmithProperties.com ']
    });
    expect(body.policy).toBe('person-form');
  });
});
