#!/usr/bin/env npx tsx
/**
 * Converts seed-snapshot.json → convex/seedData.ts
 *
 * Bridges the agent-generated JSON snapshots to the TypeScript file
 * consumed by convex/seed.ts, eliminating manual copy-paste.
 *
 * Usage:
 *   npx tsx scripts/snapshot-to-seed-data.ts
 *   npx tsx scripts/snapshot-to-seed-data.ts --snapshot path/to/snapshot.json
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, resolve } from 'path';

import type { TemplateSnapshot } from './lib/seed-pipeline';

// ============================================================================
// CLI
// ============================================================================

const args = process.argv.slice(2);
const snapshotFlag = args.indexOf('--snapshot');
const snapshotPath = snapshotFlag !== -1 && args[snapshotFlag + 1]
	? resolve(args[snapshotFlag + 1])
	: join(import.meta.dirname || process.cwd(), 'seed-snapshot.json');

const outputPath = join(import.meta.dirname || process.cwd(), '..', 'convex', 'seedData.ts');

// ============================================================================
// Read snapshot
// ============================================================================

if (!existsSync(snapshotPath)) {
	console.error(`ERROR: Snapshot file not found: ${snapshotPath}`);
	console.error('Run the agent pipeline first:  npx tsx scripts/seed-with-agents.ts');
	process.exit(1);
}

const raw = readFileSync(snapshotPath, 'utf-8');
const snapshots: Record<string, TemplateSnapshot> = JSON.parse(raw);
const templates = Object.values(snapshots);

if (templates.length === 0) {
	console.error('ERROR: Snapshot file is empty.');
	process.exit(1);
}

console.log(`Read ${templates.length} templates from ${snapshotPath}`);

// ============================================================================
// Generate TypeScript
// ============================================================================

function escapeString(s: string): string {
	return s
		.replace(/\\/g, '\\\\')
		.replace(/"/g, '\\"')
		.replace(/\n/g, '\\n')
		.replace(/\t/g, '\\t');
}

function toJsonLiteral(value: unknown, indent: number): string {
	const pad = '  '.repeat(indent);
	const innerPad = '  '.repeat(indent + 1);

	if (value === null || value === undefined) return 'null';
	if (typeof value === 'boolean') return String(value);
	if (typeof value === 'number') return String(value);
	if (typeof value === 'string') return `"${escapeString(value)}"`;

	if (Array.isArray(value)) {
		if (value.length === 0) return '[]';
		const items = value.map((v) => `${innerPad}${toJsonLiteral(v, indent + 1)}`);
		return `[\n${items.join(',\n')},\n${pad}]`;
	}

	if (typeof value === 'object') {
		const entries = Object.entries(value as Record<string, unknown>);
		if (entries.length === 0) return '{}';
		const fields = entries.map(([k, v]) => {
			const key = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : `"${escapeString(k)}"`;
			return `${innerPad}${key}: ${toJsonLiteral(v, indent + 1)}`;
		});
		return `{\n${fields.join(',\n')},\n${pad}}`;
	}

	return String(value);
}

function templateToTS(t: TemplateSnapshot, index: number): string {
	const lines: string[] = [];
	lines.push(`  // ── ${index + 1}. ${t.title.slice(0, 50)} ──`);
	lines.push('  {');
	lines.push(`    slug: "${escapeString(t.slug)}",`);
	lines.push(`    title: "${escapeString(t.title)}",`);
	lines.push(`    description: "${escapeString(t.description)}",`);
	lines.push(`    category: "${escapeString(t.category)}",`);
	lines.push(`    topics: ${toJsonLiteral(t.topics, 2)},`);
	lines.push(`    type: "${t.type}",`);
	lines.push(`    deliveryMethod: "${t.deliveryMethod}",`);
	lines.push(`    preview: "${escapeString(t.preview)}",`);
	lines.push(`    messageBody: "${escapeString(t.messageBody)}",`);
	lines.push(`    countryCode: "${t.countryCode}",`);
	lines.push(`    sources: ${toJsonLiteral(t.sources, 2)},`);
	lines.push(`    researchLog: ${toJsonLiteral(t.researchLog, 2)},`);
	lines.push(`    recipientConfig: ${toJsonLiteral(t.recipientConfig, 2)},`);
	lines.push(`    deliveryConfig: ${toJsonLiteral(t.deliveryConfig, 2)},`);
	if (t.cwcConfig) {
		lines.push(`    cwcConfig: ${toJsonLiteral(t.cwcConfig, 2)},`);
	}
	lines.push(`    contentHash: "${escapeString(t.contentHash)}",`);
	lines.push(`    scopes: ${toJsonLiteral(t.scopes, 2)},`);
	lines.push(`    jurisdictions: ${toJsonLiteral(t.jurisdictions, 2)},`);

	lines.push('  },');

	return lines.join('\n');
}

// ============================================================================
// Write output
// ============================================================================

const header = `/**
 * Seed template data — loaded by convex/seed.ts
 *
 * AUTO-GENERATED by scripts/snapshot-to-seed-data.ts
 * from: ${snapshotPath}
 * at:   ${new Date().toISOString()}
 *
 * To regenerate:
 *   1. npx tsx scripts/seed-with-agents.ts      (produces seed-snapshot.json)
 *   2. npx tsx scripts/snapshot-to-seed-data.ts  (writes this file)
 */

export interface SeedScope {
  countryCode: string;
  regionCode?: string;
  localityCode?: string;
  districtCode?: string;
  displayText: string;
  scopeLevel: "country" | "region" | "locality" | "district";
  confidence: number;
  extractionMethod: string;
}

export interface SeedJurisdiction {
  jurisdictionType: string;
  stateCode?: string;
  congressionalDistrict?: string;
  countyName?: string;
  cityName?: string;
}

export interface SeedCwcConfig {
  enabled: boolean;
  priority?: 'normal' | 'high' | 'urgent';
  tracking_enabled?: boolean;
  office_codes?: string[];
}

export interface SeedTemplate {
  slug: string;
  title: string;
  description: string;
  category: string;
  topics: string[];
  type: string;
  deliveryMethod: string;
  preview: string;
  messageBody: string;
  countryCode: string;
  sources: Array<{ num: number; title: string; url: string; type: string }>;
  researchLog: string[];
  recipientConfig: Record<string, unknown>;
  deliveryConfig: Record<string, unknown>;
  cwcConfig?: SeedCwcConfig;
  contentHash: string;
  scopes: SeedScope[];
  jurisdictions: SeedJurisdiction[];
}
`;

const body = templates.map((t, i) => templateToTS(t, i)).join('\n');
const output = `${header}\nexport const SEED_TEMPLATES: SeedTemplate[] = [\n${body}\n];\n`;

writeFileSync(outputPath, output, 'utf-8');

console.log(`Wrote ${templates.length} templates to ${outputPath}`);
console.log('Done.');
